#!/usr/bin/env bash
# Kills the 4-to_infinity_and_beyond process

pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
    # If the process is running, use kill to stop it
    kill "$pid"
    echo "Process stopped successfully."
else
    echo "Process is not running."
fi
